name = "allamo-pmo-stage"
pages_build_output_dir = "public"
compatibility_date = "2026-08-20"

[env.production]
compatibility_date = "2026-08-01"

[[env.production.d1_databases]]
database_id = "72e2f6a0-3d22-4d65-a820-4a9b9ea88321"
binding = "DB"
database_name = "DB"

[env.production.ai]
binding = "AI"
