interface D1Result<T=Record<string,unknown>>{success?:boolean;results?:T[];meta?:Record<string,unknown>}
interface D1PreparedStatement{bind(...values:unknown[]):D1PreparedStatement;first<T=Record<string,unknown>>(column?:string):Promise<T|null>;all<T=Record<string,unknown>>():Promise<D1Result<T>>;run<T=Record<string,unknown>>():Promise<D1Result<T>>}
interface D1Database{prepare(query:string):D1PreparedStatement;batch<T=Record<string,unknown>>(statements:D1PreparedStatement[]):Promise<D1Result<T>[]>;exec(query:string):Promise<unknown>}
interface VectorizeMatch{id:string;score:number;metadata?:Record<string,unknown>}
interface VectorizeMatches{matches:VectorizeMatch[]}
interface VectorizeIndex{query(vector:number[],options?:Record<string,unknown>):Promise<VectorizeMatches>;upsert(vectors:Array<{id:string;values:number[];metadata?:Record<string,unknown>}>):Promise<unknown>}
interface RateLimit{limit(options:{key:string}):Promise<{success:boolean}>}
interface R2Bucket{put(key:string,value:string|ArrayBuffer|ArrayBufferView|ReadableStream,options?:Record<string,unknown>):Promise<unknown>;delete(key:string):Promise<void>}
interface ScheduledEvent{scheduledTime:number;cron:string}
